### ISSUE TITLE
I hope you can add support for empty frames.

### ISSUE THREAD

**Issue by RC1844** [miu200521358/3d-pose-baseline-vmd#10]
1. Windows 10 x64
2. tensorflow 1.31
3. python 3.71
4. Traceback (most recent call last):
  File "src/openpose_3dpose_sandbox_vmd.py", line 484, in <module>
    tf.app.run()
  File "F:\Program Files (x86)\Miniconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "src/openpose_3dpose_sandbox_vmd.py", line 211, in main
    center_2d_x, center_2d_y  = camera_center(openpose_output_dir) #動画の中心座標（動画の解像度の半分）
  File "src/openpose_3dpose_sandbox_vmd.py", line 403, in camera_center
    x = float(sf.readline().replace('\n', '')) / 2
ValueError: could not convert string to float:

I am sorry to have added trouble to you, but I think this is reasonable.
The person in the video I used is incomplete, so it will have empty frames, I hope you can add support for empty frames.

**Comment by timtensor** [comment]
Hi i would suggest to run it in ubuntu enviroment It works fine in Ubuntu

**Comment by RC1844** [comment]
> 嗨我建议在ubuntu环境中运行它在Ubuntu中工作正常

Hi，I know the problem is there. The above is that I didn't seriously read the self-reported results. I have solved the problem. But I still want to be able to skip this error.
>  最初のフレームに人数分のデータがありません。
>  There is no data for the number of people in the first frame.

**Comment by timtensor** [comment]
ok  i hope it solves your issue . There are some modifications to be done , if you want to run the original imnplementation of the 3d-pose-baseline. I havent managed to run this version the code or to generate an animation. I am not a game developer , so i dont know .  Did you manage to generate an animation in unity based on the original 3d -pose estimation

**Comment by RC1844** [comment]
Oh no, I don't have any knowledge.
